# Generated by Django 4.0.4 on 2024-09-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('english_level', models.CharField(max_length=50)),
                ('technologies', models.CharField(blank=True, max_length=555, null=True)),
                ('seniority_level', models.CharField(max_length=55)),
                ('date_posted', models.CharField(blank=True, max_length=150, null=True)),
                ('source', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
