# Generated by Django 4.0.4 on 2024-08-30 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('vacancy_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('technology', models.CharField(max_length=255)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('views_popularity', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('vacancy_count', models.IntegerField()),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping_data.technology')),
            ],
            options={
                'verbose_name_plural': 'Historical Data',
            },
        ),
    ]
