# Generated by Django 4.0.4 on 2024-10-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('english_level', models.CharField(blank=True, max_length=50, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=55, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('technologies', models.ManyToManyField(to='scraping_data.technology')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
