# Generated by Django 4.0.4 on 2024-09-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_data', '0002_joblisting_delete_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='views_popularity',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
