# Generated by Django 4.0.4 on 2024-09-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_data', '0003_alter_joblisting_views_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
