# Generated by Django 4.0.4 on 2024-09-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_data', '0005_alter_joblisting_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='views_popularity',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='seniority_level',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='technologies',
            field=models.CharField(max_length=555),
        ),
        migrations.DeleteModel(
            name='HistoricalData',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
