# Generated by Django 4.0.4 on 2024-09-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='date_posted',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='english_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='technologies',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
