# Generated by Django 4.0.4 on 2024-09-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_data', '0002_alter_joblisting_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='technologies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
