# Generated by Django 4.0.4 on 2024-09-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_data', '0003_alter_joblisting_date_posted_alter_joblisting_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='seniority_level',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='technologies',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='technologies',
            field=models.ManyToManyField(to='scraping_data.technology'),
        ),
    ]
